[pytest]
filterwarnings =
    ignore:.*enablePackrat.*:DeprecationWarning
    ignore:.*setParseAction.*:DeprecationWarning
    ignore:.*oneOf.*:DeprecationWarning
    ignore:.*delimitedList.*:DeprecationWarning
    ignore:.*infixNotation.*:DeprecationWarning
    ignore:.*parseString.*:DeprecationWarning
